<?php

namespace ContainerNeceSOh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_YpC_PEiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.YpC.PEi' shared service.
     *
     * @return \http\Env\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::createAppointment()": the $request argument is type-hinted with the non-existent class or interface: "http\\Env\\Request".');
    }
}
