<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHfeGsGg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHfeGsGg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHfeGsGg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHfeGsGg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHfeGsGg\App_KernelDevDebugContainer([
    'container.build_hash' => 'HfeGsGg',
    'container.build_id' => 'e55e0e96',
    'container.build_time' => 1746551950,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHfeGsGg');
