<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXTTPKtj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXTTPKtj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXTTPKtj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXTTPKtj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXTTPKtj\App_KernelDevDebugContainer([
    'container.build_hash' => 'XTTPKtj',
    'container.build_id' => '310aa43f',
    'container.build_time' => 1746556351,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXTTPKtj');
