<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNuHri3u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNuHri3u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNuHri3u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNuHri3u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNuHri3u\App_KernelDevDebugContainer([
    'container.build_hash' => 'NuHri3u',
    'container.build_id' => 'cdf35165',
    'container.build_time' => 1746638693,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNuHri3u');
